### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Crazzyguyy** [NoahvdAa/nTrivia#1]
Hello,I was wondering if you could add an option in the config.yml file of nTrivia to set how many players need to be online to ask the question.
EX:
if only 3 players are online no questions are asked, but if there is 4 of more people, then the normal trivia questions are asked.
Thank you :)

**Comment by NoahvdAa** [comment]
Thank you for the suggestion! I'll get to implementing it soon.

**Comment by NoahvdAa** [comment]
Added in dcda4e5.
