### ISSUE TITLE
Plugin not functioning

### ISSUE THREAD

**Issue by IsXGeo** [NoahvdAa/nTrivia#2]
I've installed v1.2.0 of the plugin on my 1.16.1 Paper server and the plugin does not seem to ask any questions. There are no errors displaying in console and there are no messages being displayed in game. No questions, no announcing the loss message.

Even if I leave the plugin config as default there are no changes. Are there dependencies that I am supposed to have by chance?

Any help appreciated

**Comment by NoahvdAa** [comment]
This has been fixed in fdef2cf. The version on Spigot has been updated too.
