### ISSUE TITLE
Possessive Nouns

### ISSUE THREAD

**Issue by Spooooc** [NoahvdAa/nTrivia#3]
Fantastic plugin, really good job.
My only thing is questions with possessive nouns mess up the entire config, because it recognizes it as the beginning / ending of a question rather than a string (for example, the question: Where is Harry Potter's scar located). it just glitches out the config.
Would you be able to change the syntax to quotation marks instead? Is there a different way around this issue?
Thanks a lot.

**Comment by NoahvdAa** [comment]
Since this issue was closed, I'm going to assume you already figured it out. Just for future reference, this is how  you can do it (two apostrophes instead of one):
`- 'Where is Harry Potter''s scar located|||answerone|||answertwo|||...'`
