### ISSUE TITLE
Update for 1.18.X ?

### ISSUE THREAD

**Issue by HarrisMcCallen** [NoahvdAa/nTrivia#4]
Love the plugin, but it stops working properly after a time. 
When this happens, it asks the question, mutes the correct answer from players, but the answer is not registered, the "won:" message is not triggered, and the time will expire. 
Additionally, the reward function does not seem to work at all.
I believe some of these issues could be due to an incompatible server version?
My server is running git-Paper-290 (MC 1.18.2) 
In the event this plugin could be patched or updated for compatibility, we would all appreciate it greatly!

**Comment by NoahvdAa** [comment]
Do you have an estimate of how long the plugin works properly before it breaks down? There haven't been any API changes that should affect compatibility with nTrivia that I know of.

**Comment by HarrisMcCallen** [comment]
Thanks for getting back to me on this. I have neither been online to
witness it fail, nor have I been able to monitor the console to see what
might be happening at the time. It's possible that it occurs during a
restart, but I don't have proof of that yet.
I'll re-enable the plugin and try to monitor it over the next few days.

**Comment by HarrisMcCallen** [comment]
The plugin seems to break after a server restart (which happens
automatically, four times daily.)
To test this, I re-installed the plugin from scratch, and started the
server. I dropped in a known working backup of the custom config.yml to set
the nTrivia prefix to our virtual assistant Lisa. (The issue occurs with
the default as well.)
I used /ntrivia reload - and everything works normally, for as long as I
could tell.
Then I restarted the server.
Following the restart, everything appears to be working correctly, but
nTrivia is unable to process the correct answer to the questions. Players
can type the answers, but they will not appear on-screen, and the plugin
doesn't react.
I grabbed some code from the console at the exact moment this was
occurring. I typed the answer to the questions, which is, pumpkins.

*13.05 05:06:00 [Server] INFO [Assistant][Lisa] ? You have 30 seconds to
answer the following question... Between Pumpkins and Diamonds, which is
more rare to find? (This is the "announce:" line from config.yml)*
13.05 05:06:17 [Server] ERROR Thread Async Chat Thread - #1 failed main
thread check: ChunkHolder update
13.05 05:06:17 [Server] INFO java.lang.Throwable: null
13.05 05:06:17 [Server] INFO at
org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.level.ChunkHolder.addToBroadcastMap(ChunkHolder.java:329)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.level.ChunkHolder.blockChanged(ChunkHolder.java:289)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.level.ServerChunkCache.blockChanged(ServerChunkCache.java:1121)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.level.ServerLevel.sendBlockUpdated(ServerLevel.java:1557)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.world.level.block.entity.CommandBlockEntity$1.onUpdated(CommandBlockEntity.java:45)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.world.level.BaseCommandBlock.sendMessage(BaseCommandBlock.java:180)
~[?:?]
13.05 05:06:17 [Server] INFO at
org.bukkit.craftbukkit.v1_18_R2.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:33)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
org.bukkit.command.CommandSender.sendMessage(CommandSender.java:128)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
13.05 05:06:17 [Server] INFO at
net.kyori.adventure.audience.Audience.sendMessage(Audience.java:254)
~[adventure-api-4.10.1.jar:?]
13.05 05:06:17 [Server] INFO at
net.kyori.adventure.audience.Audience.sendMessage(Audience.java:228)
~[adventure-api-4.10.1.jar:?]
13.05 05:06:17 [Server] INFO at
org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1766)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1738)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcastMessage(CraftServer.java:642)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
org.bukkit.Bukkit.broadcastMessage(Bukkit.java:420)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
13.05 05:06:17 [Server] INFO at
me.noahvdaa.ntrivia.Events.asyncPlayerChat(Events.java:71)
~[nTrivia-1.2.1.jar:?]
13.05 05:06:17 [Server] INFO at
com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown
Source) ~[?:?]
13.05 05:06:17 [Server] INFO at
org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
13.05 05:06:17 [Server] INFO at
co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
13.05 05:06:17 [Server] INFO at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
13.05 05:06:17 [Server] INFO at
io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:194)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:66)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2223)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2134)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2100)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40)
~[?:?]
13.05 05:06:17 [Server] INFO at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
~[?:?]
13.05 05:06:17 [Server] INFO at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
~[?:?]
13.05 05:06:17 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
13.05 05:06:17 [Server] ERROR Could not pass event AsyncPlayerChatEvent to
nTrivia v1.2.1
13.05 05:06:17 [Server] INFO java.lang.IllegalStateException: Asynchronous
ChunkHolder update!
13.05 05:06:17 [Server] INFO at
org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.level.ChunkHolder.addToBroadcastMap(ChunkHolder.java:329)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.level.ChunkHolder.blockChanged(ChunkHolder.java:289)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.level.ServerChunkCache.blockChanged(ServerChunkCache.java:1121)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.level.ServerLevel.sendBlockUpdated(ServerLevel.java:1557)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.world.level.block.entity.CommandBlockEntity$1.onUpdated(CommandBlockEntity.java:45)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.world.level.BaseCommandBlock.sendMessage(BaseCommandBlock.java:180)
~[?:?]
13.05 05:06:17 [Server] INFO at
org.bukkit.craftbukkit.v1_18_R2.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:33)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
org.bukkit.command.CommandSender.sendMessage(CommandSender.java:128)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
13.05 05:06:17 [Server] INFO at
net.kyori.adventure.audience.Audience.sendMessage(Audience.java:254)
~[adventure-api-4.10.1.jar:?]
13.05 05:06:17 [Server] INFO at
net.kyori.adventure.audience.Audience.sendMessage(Audience.java:228)
~[adventure-api-4.10.1.jar:?]
13.05 05:06:17 [Server] INFO at
org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1766)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1738)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcastMessage(CraftServer.java:642)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
org.bukkit.Bukkit.broadcastMessage(Bukkit.java:420)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
13.05 05:06:17 [Server] INFO at
me.noahvdaa.ntrivia.Events.asyncPlayerChat(Events.java:71)
~[nTrivia-1.2.1.jar:?]
13.05 05:06:17 [Server] INFO at
com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown
Source) ~[?:?]
13.05 05:06:17 [Server] INFO at
org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
13.05 05:06:17 [Server] INFO at
co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
13.05 05:06:17 [Server] INFO at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
13.05 05:06:17 [Server] INFO at
io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:194)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:66)
~[paper-1.18.2.jar:git-Paper-290]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2223)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2134)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2100)
~[?:?]
13.05 05:06:17 [Server] INFO at
net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40)
~[?:?]
13.05 05:06:17 [Server] INFO at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
~[?:?]
13.05 05:06:17 [Server] INFO at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
~[?:?]
13.05 05:06:17 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
*13.05 05:06:30 [Server] INFO [Assistant][Lisa] ? Ding! I will ask another
question in a few minutes. * *(This is the "notintime:" line from
config.yml - although I answered correctly, the "won:" event never
happened.)*

At this point, restarting won't help. Reloading the plugin does not change
the outcome. The only way to fix this, is to delete the plugin and
directories entirely, restart the server without them, install a fresh copy
of the plugin, and restart the server a second time, at which point
everything will work fine, until the next restart. I even tried renaming
the nTrivia-1.2.1.jar file as "nTrivia-1.2.1.jar.pause" and restarting, so
it would not load, then renaming it again as "nTrivia-1.2.1.jar" and
restarting again, but that does not work - the plugin needs to be
completely deleted from the server, as explained above, before it can work
again.

Again, it isn't the config.yml at fault, as this can be repeated with the
same result, whether the default config file is used, or by using our
custom "Lisa" version.

Hopefully this information is helpful. Let me know if you need more.

**Comment by NoahvdAa** [comment]
Can reproduce, related to PaperMC/Paper#7511. I'll push a fix in a bit.

**Comment by NoahvdAa** [comment]
Fixed in [1.2.2](https://github.com/NoahvdAa/nTrivia/releases/tag/1.2.2).

**Comment by HarrisMcCallen** [comment]
Great, thanks! We do really love the plugin, and our players have given a
lot of positive feedback since its implementation.
Using our pseudo-AI assistant is even more fun, as players already enjoy
interacting with her, and by tying her name to the functions of this
plugin, it gives the illusion that she's autonomously engaging with them.

On a possibly related note, we have been unable to use the reward system.
Using "give" as-is, or changing to the command-block style
"minecraft:give.." (or "eco" for currency) does not appear to work. For
now, I just hashtagged the "RewardCommands:" line, but it would be fun to
hand out rewards. It appears that this is capable of multiple lines, so I'm
curious, if so, is that a random chance of any one of the reward lines "-
give {player} diamond 1" or would it just do all of them?
